Updating Android Native Checkout Version to 1.2.0
paypal/paypal-android pull request #214
Opened 2023-11-15 21:37 UTC by chpypl

Thank you for your contribution to PayPal. 

> Before submitting this PR, note that we cannot accept language translation PRs. We have a dedicated localization team to provide the translations. If there is an error in a specific translation, you may open an issue and we will escalate it to the localization team.

### Summary of changes

Updating the Android Native Checkout SDK to 1.1.0

 ### Checklist

 - [x] Added a changelog entry

### Authors
> List GitHub usernames for everyone who contributed to this pull request.

-

2023-11-15 21:39 UTC, sshropshire approved these changes

2023-11-16 17:41 UTC, warmkesselj approved these changes

2023-11-17 17:46 UTC, jaxdesmarais requested changes
Can we update properties and the changelog to match the BT android PR: https://github.com/braintree/braintree_android/pull/829

2023-11-17 18:04 UTC, jaxdesmarais commented on CHANGELOG.md
> +  * Add `email` to `PayPalNativeCheckoutRequest`
```suggestion
  * Add `userAuthenticationEmail` to `PayPalNativeCheckoutRequest`
```

2023-11-17 18:04 UTC, jaxdesmarais commented on PayPalNativePayments/src/main/java/com/paypal/android/paypalnativepayments/PayPalNativeCheckoutClient.kt
> +                val authConfig: AuthConfig? = request.email?.let { AuthConfig(it) }
```suggestion
                val authConfig: AuthConfig? = request.userAuthenticationEmail?.let { AuthConfig(it) }
```

2023-11-17 18:04 UTC, jaxdesmarais commented on PayPalNativePayments/src/main/java/com/paypal/android/paypalnativepayments/PayPalNativeCheckoutRequest.kt
> +    val email: String? = null
```suggestion
    val userAuthenticationEmail: String? = null
```

2023-11-17 18:04 UTC, jaxdesmarais commented on PayPalNativePayments/src/main/java/com/paypal/android/paypalnativepayments/PayPalNativeCheckoutRequest.kt
> +     * Optional: The email for preloading authentication
```suggestion
     * Optional: User email to initiate a quicker authentication flow in cases where the user has a PayPal Account with the same email.
```

2023-11-17 19:55 UTC, jaxdesmarais approved these changes

2023-11-17 21:08 UTC, merged